#tomcat访问的端口
server:
  port: 9527
  tomcat:
    uri-encoding: utf-8


spring:
  application:
    name: cloud-zuul-service


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: producer-zuul9527
    prefer-ip-address: true #显示ip地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /atguigu
  ignored-services: "*"
  routes:
    mydept.serviceId: cloud-producer-service
    mydept.path: /mydept/**

